-- เติมชื่อภาษาอังกฤษ (name_en) ให้ defect_category / defect_sub_category
-- จับคู่ด้วยชื่อไทย ไม่ใช่ id เพราะ id อาจไม่ตรงกันระหว่าง dev/prod
-- sub-category ชื่อซ้ำกันเยอะ (เช่น "สีเลอะ" มีแทบทุกหมวด) จึงแปลแค่ชื่อที่ไม่ซ้ำ แล้วอัปเดตทุกแถวที่ชื่อตรงกัน
-- อัปเดตเฉพาะแถวที่ name_en ยังว่าง เพื่อไม่ทับคำแปลที่ admin แก้เอง — รันซ้ำได้
BEGIN;

ALTER TABLE defect_category ADD COLUMN IF NOT EXISTS name_en varchar(255);
ALTER TABLE defect_sub_category ADD COLUMN IF NOT EXISTS name_en varchar(255);

-- ── หมวดหลัก ─────────────────────────────────────────────────────────────
UPDATE defect_category AS c
SET name_en = m.en
FROM (VALUES
  ('งานผนังและพื้น', 'Walls & Floors'),
  ('งานระบบประปา', 'Plumbing System'),
  ('งานระบบไฟฟ้า', 'Electrical System'),
  ('งานโครงสร้าง', 'Structural Work'),
  ('ประตู', 'Doors'),
  ('ประตูกระจก', 'Glass Doors'),
  ('Door stopper', 'Door Stopper'),
  ('หน้าต่าง', 'Windows'),
  ('มุ้งลวด', 'Insect Screens'),
  ('ผ้าม่าน', 'Curtains'),
  ('มู่ลี่', 'Blinds'),
  ('ม่านม้วน', 'Roller Blinds'),
  ('ปลั๊ก', 'Power Outlets'),
  ('แสงสว่าง', 'Lighting'),
  ('ไฟฟ้า', 'Electrical'),
  ('Juntion Box', 'Junction Box'),
  ('เครื่องดูดควัน', 'Range Hood'),
  ('เครื่องล้างจาน', 'Dishwasher'),
  ('เครื่องปรับอากาศ', 'Air Conditioning'),
  ('กระเบื้อง', 'Tiles'),
  ('หินอ่อน', 'Marble'),
  ('หินธรรมชาติ', 'Natural Stone'),
  ('หินเทียม,หินสังเคราะห์', 'Engineered / Synthetic Stone'),
  ('พื้นกระเบื้องยาง', 'Vinyl Tile Flooring'),
  ('พื้นกระเบื้องยาง SPC', 'SPC Vinyl Flooring'),
  ('พื้นลามิเนต', 'Laminate Flooring'),
  ('พื้นไม้', 'Wood Flooring'),
  ('พื้นไม้ปาเก้', 'Parquet Flooring'),
  ('พื้นเอนจิเนียร์วู้ด', 'Engineered Wood Flooring'),
  ('พื้นคอนกรีต', 'Concrete Floor'),
  ('พื้นแสตมป์คอนกรีต', 'Stamped Concrete Floor'),
  ('พื้นทรายล้าง', 'Exposed Aggregate Floor'),
  ('พื้นไม้ภายนอก', 'Exterior Wood Decking'),
  ('สวน และบริเวณ', 'Garden & Grounds'),
  ('บัวพื้น', 'Skirting Board'),
  ('บัวฝ้าเพดาน', 'Ceiling Cornice'),
  ('บัวผนัง', 'Wall Moulding'),
  ('บัวปูน', 'Cement Moulding'),
  ('กระจก', 'Glass & Mirrors'),
  ('ผนัง', 'Walls'),
  ('วอลล์เปเปอร์', 'Wallpaper'),
  ('เฟอร์นิเจอร์', 'Furniture'),
  ('ฝ้าเพดาน', 'Ceiling'),
  ('ฝ้าภายนอก', 'Exterior Ceiling'),
  ('เชิงชาย', 'Fascia Board'),
  ('เหล็กตกแต่ง', 'Decorative Steel'),
  ('ระบบป้องกันปลวก', 'Termite Protection System'),
  ('ตู้จดหมาย', 'Mailbox'),
  ('ถังขยะ', 'Waste Bin'),
  ('สปริงเกอร์ดับเพลิง', 'Fire Sprinklers'),
  ('เครื่องทำความร้อน/เครื่องดูดควัน', 'Heater / Range Hood'),
  ('สระว่ายน้ำ', 'Swimming Pool'),
  ('ประปา', 'Plumbing'),
  ('สุขภัณฑ์', 'Sanitary Ware'),
  ('อ่างล้างจาน', 'Kitchen Sink'),
  ('เครื่องทำน้ำอุ่น/น้ำร้อน', 'Water Heater'),
  ('เครื่องปั๊มน้ำ', 'Water Pump'),
  ('สุขาภิบาล', 'Sanitation & Drainage'),
  ('FD/RD', 'Floor Drain / Roof Drain'),
  ('หลังคา', 'Roof'),
  ('ฉนวนกันความร้อน', 'Thermal Insulation'),
  ('แผ่นกันความร้อน', 'Radiant Barrier Sheet'),
  ('ราวกันตก', 'Guardrail'),
  ('ราวบันได', 'Stair Handrail'),
  ('บันได', 'Stairs'),
  ('ประตูรั้ว', 'Gate'),
  ('รั้ว', 'Fence'),
  ('บ่อบำบัด', 'Septic Tank'),
  ('บ่อดักไขมัน', 'Grease Trap'),
  ('Ground rod', 'Ground Rod'),
  ('โครงสร้าง', 'Structure')
) AS m(th, en)
WHERE btrim(c.name) = m.th
  AND c.name_en IS NULL;

-- ── หมวดย่อย (ชื่อไม่ซ้ำ) ─────────────────────────────────────────────────
UPDATE defect_sub_category AS s
SET name_en = m.en
FROM (VALUES
  -- หมวดย่อยชุดเก่า (category 1-4)
  ('ผิวหนังและสี', 'Wall surface & paint'),
  ('งานปูพื้นกระเบื้อง', 'Floor tiling'),
  ('สุขภัณฑ์และอุปกรณ์', 'Sanitary ware & fittings'),
  ('ระบบระบายน้ำ', 'Drainage system'),
  ('ระบบแสงสว่าง', 'Lighting system'),
  ('งานฝ้าและเพดาน', 'Ceiling work'),
  ('งานประตูและหน้าต่าง', 'Doors & windows'),
  ('งานระเบียงและภายนอก', 'Balcony & exterior'),
  ('งานเฟรมและอลูมิเนียม', 'Frames & aluminium'),
  ('งานเซาะร่อง/รอยต่อ', 'Grooves / joints'),
  ('งานสีและทำความสะอาด', 'Painting & cleaning'),

  -- ทั่วไป (ใช้ซ้ำหลายหมวด)
  ('อื่นๆ', 'Other'),
  ('อื่นๆ…..', 'Other…'),
  ('รายการอื่นๆ…..', 'Other items…'),
  ('ชำรุด', 'Damaged'),
  ('แตกชำรุด', 'Broken / damaged'),
  ('แตก/ชำรุด', 'Cracked / damaged'),
  ('เป็นรอย', 'Scratched'),
  ('รอยขีดข่วน', 'Scratches'),
  ('รอยขีดเขียน', 'Marks / scribbles'),
  ('รอยถลอก', 'Scuff marks'),
  ('รอยบิ่น', 'Chipped'),
  ('รอบบิ่น', 'Chipped'),
  ('บิ่น', 'Chipped'),
  ('รอยบุบ', 'Dented'),
  ('บุบ', 'Dented'),
  ('รอยร้าว', 'Crack'),
  ('รอยร้าว รอยต่อ', 'Crack at joint'),
  ('รอยร้าวรอยต่อ', 'Crack at joint'),
  ('รอยร้าวทะลุ', 'Through crack'),
  ('รอยแตก', 'Fracture'),
  ('แตก', 'Cracked'),
  ('รอยเจาะ', 'Drill holes'),
  ('เป็นรู', 'Holes'),
  ('รั่ว', 'Leaking'),
  ('น้ำรั่วซึม', 'Water leakage'),
  ('น้ำขัง', 'Water pooling'),
  ('น้ำเข้า', 'Water ingress'),
  ('พบคราบน้ำ', 'Water stains found'),
  ('พบความชื้น', 'Moisture detected'),
  ('พบความซื้น', 'Moisture detected'),
  ('บวม', 'Swollen'),
  ('บวม/พอง', 'Swollen / bulging'),
  ('เป็นสนิม', 'Rusty'),
  ('ทำความสะอาด', 'Needs cleaning'),
  ('ตรวจสอบไม่ได้', 'Unable to inspect'),
  ('ยังไม่ตรวจสอบ', 'Not yet inspected'),
  ('ยังไม่ได้ตรวจสอบ', 'Not yet inspected'),
  ('ยังไม่พร้อมตรวจสอบ', 'Not ready for inspection'),
  ('ยังไม่ติดตั้ง', 'Not installed'),
  ('ยังไม่ได้ติดตั้ง', 'Not installed'),
  ('ยังไม่มีการติดตั้ง', 'Not installed'),
  ('ยังไม่เก็บงาน', 'Finishing not done'),
  ('เก็บงานไม่เรียบร้อย', 'Untidy finishing'),
  ('ใช้งานยาก', 'Difficult to use'),
  ('เครื่องไม่ทำงาน', 'Unit not working'),
  ('ไฟไม่เข้า', 'No power'),
  ('ไฟไม่ติด', 'Light not working'),
  ('อุปกรณ์ไม่ครบ', 'Missing components'),
  ('อุปกรณ์ชำรุด', 'Equipment damaged'),
  ('อุปกรณ์เป็นสนิม', 'Rusty hardware'),
  ('อุปกรณ์เป็นรอย', 'Hardware scratched'),
  ('อุปกรณ์เหลือง', 'Components yellowed'),
  ('ขอบคม', 'Sharp edges'),
  ('เหลี่ยมคม', 'Sharp edges'),
  ('เหลี่ยมไม่ตรง', 'Edges not straight'),
  ('มุมไม่ตรง', 'Corners not straight'),
  ('ผิวไม่เรียบ', 'Uneven surface'),
  ('ผิวเป็นเม็ดทราย', 'Sandy / grainy surface'),
  ('ไม่ได้ระดับ', 'Not level'),
  ('ฉีกขาด', 'Torn'),
  ('ถลอก/ขาด', 'Frayed / torn'),
  ('โก่ง/งอ', 'Bent / warped'),
  ('เหล็กโผล่', 'Exposed steel'),
  ('เหล็กงอ', 'Bent steel'),
  ('เหล็กโก่งงอ', 'Steel bent'),
  ('เหล็กโก่ง งอ', 'Steel bent'),
  ('พบเศษวัสดุไม่ใช้งาน', 'Leftover debris found'),
  ('พบเศษวัสดุไม่ได้ใช้งาน', 'Leftover debris found'),
  ('พบวัสดุไม่ใช้งาน', 'Unused materials found'),
  ('พบมูลสัตว์', 'Animal droppings found'),
  ('พบคราบมูลสัตว์', 'Animal dropping stains'),

  -- คราบ / สี
  ('คราบฝังแน่น', 'Stubborn stains'),
  ('คราบสกปรก', 'Dirt stains'),
  ('เลอะคราบสกปรก', 'Dirty / stained'),
  ('คราบสนิม', 'Rust stains'),
  ('ครบสนิม', 'Rust stains'),
  ('คราบด่าง', 'Blotchy stains'),
  ('คราบกาว', 'Adhesive residue'),
  ('คราบซิลิโคน', 'Silicone residue'),
  ('คราบปูน', 'Mortar stains'),
  ('สีเลอะ', 'Paint smudges'),
  ('เลอะสี', 'Paint smudges'),
  ('สีด่าง', 'Blotchy paint'),
  ('สีเพี้ยน', 'Colour mismatch'),
  ('สีเพื้ยน', 'Colour mismatch'),
  ('สีบวม', 'Paint blistering'),
  ('สีบวม/พอง', 'Paint blistering / bubbling'),
  ('สีร่อน', 'Paint flaking'),
  ('สีหลุดร่อน', 'Paint peeling'),
  ('สีลอก/หลุดล่อน', 'Paint peeling / flaking'),
  ('สีลอก/ร่อน', 'Paint peeling / flaking'),
  ('ยังไม่ทาสี', 'Not yet painted'),
  ('ทาสีไม่แล้วเสร็จ', 'Painting incomplete'),
  ('กันสีไม่ตรง', 'Crooked paint line'),
  ('กันสีรอยต่อไม่ตรง', 'Crooked paint line at joint'),

  -- การติดตั้ง
  ('ติดตั้งเอียง', 'Installed crooked'),
  ('ติดตั้งไม่แน่น', 'Loosely installed'),
  ('ติดตั้งไม่ลงล็อค', 'Not seated in place'),
  ('ติดตั้งไม่แล้วเสร็จ', 'Installation incomplete'),
  ('ติดตั้งไม่ได้ระดับ', 'Not level'),
  ('ติดตั้งไม่ได้ดิ่ง', 'Not plumb'),
  ('ติดตั้งไม่ได้ฉาก', 'Not square'),
  ('ติดตั้งไม่เรียบร้อย', 'Untidy installation'),
  ('ติดตั้งไม่แนบผนัง', 'Not flush against wall'),
  ('ติดตั้งไม่แนบพื้น', 'Not flush against floor'),
  ('ติดตั้งไม่แนบฝ้า', 'Not flush against ceiling'),
  ('ติดตั้งอุปกรณ์ไม่ครบ', 'Incomplete hardware installation'),
  ('ติดตั้งระยะช่องไฟไม่เท่ากัน', 'Uneven spacing'),
  ('ระยะช่องไฟไม่เท่ากัน', 'Uneven gaps'),
  ('ติดตั้งหน้ากากไม่แน่น', 'Cover plate loose'),
  ('ยังไม่ติดตั้งหน้ากาก', 'Cover plate not installed'),
  ('ยังไม่ได้ติดตั้งหน้ากาก', 'Cover plate not installed'),
  ('สกรูไม่ครบ', 'Missing screws'),
  ('ใส่สกรูไม่ครบ', 'Missing screws'),
  ('ไม่มีสกรู', 'No screws'),
  ('ไม่มีแหวนรองสกรู', 'No screw washers'),
  ('สกรูเป็นสนิม', 'Rusty screws'),
  ('สกรูป็นสนิม', 'Rusty screws'),
  ('ไม่มีจุกยางปิดหัวน็อต', 'Missing rubber screw caps'),
  ('ไม่ใส่จุกยาง', 'Missing rubber caps'),
  ('ไม่ใส่จุกยางปิดหัวกรู', 'Missing rubber screw caps'),
  ('ไม่ใส่จุกยางปิดหัวสกรู', 'Missing rubber screw caps'),

  -- รอยต่อ / ซิลิโคน / ร่อง
  ('รอยต่อไม่เรียบร้อย', 'Untidy joint'),
  ('รอยต่อไม่สนิท', 'Joint not tight'),
  ('รอยต่อกระเดิด', 'Joint lifted'),
  ('รอยต่อประกบไม่สนิท', 'Joint not tight'),
  ('รอยต่อขอบวงกบไม่เรียบร้อย', 'Untidy jamb edge joint'),
  ('รอยต่อขอบเฟรมไม่เรียบร้อย', 'Untidy frame edge joint'),
  ('รอยต่อเฟรมไม่เรียบร้อย', 'Untidy frame joint'),
  ('รอยต่อเฟรมไม่เสมอกัน', 'Frame joints not flush'),
  ('รอยต่อขอบฝ้าไม่เรียบร้อย', 'Untidy ceiling edge joint'),
  ('ซิลิโคนขอบกระจกไม่เรียบร้อย', 'Untidy silicone at glass edge'),
  ('ซิลิโคนรอยต่อขอบกระจกไม่เรียบร้อย', 'Untidy silicone at glass edge joint'),
  ('ซิลิโคนรอยต่อไม่สม่ำเสมอ', 'Uneven silicone at joints'),
  ('ซิลิโคนรอยต่อไม่เรียบร้อย', 'Untidy silicone at joints'),
  ('ยังไม่ยิงซิลิโคน', 'Silicone not yet applied'),
  ('ยังไม่ยิงซิลิโคนรอยต่อ', 'Joints not yet sealed with silicone'),
  ('รอยบากไม่เรียบร้อย', 'Untidy notch cut'),
  ('รายบากไม่เรียบร้อย', 'Untidy notch cut'),
  ('รอยบากเข้ามุมฉากไม่เรียบร้อย', 'Untidy right-angle notch cut'),
  ('เซาะร่องไม่ตรง', 'Crooked grooves'),
  ('เซาะร่องขอบวงกบไม่ตรง', 'Crooked groove at jamb edge'),
  ('เซาะร่องขอบเฟรมไม่ตรง', 'Crooked groove at frame edge'),
  ('เหลี่ยมร่องไม่ตรง', 'Groove edges not straight'),
  ('รอยเชื่อมไม่เรียบร้อย', 'Untidy welds'),
  ('รอยเชื่อมไม่เต็ม', 'Incomplete welds'),

  -- ประตู / หน้าต่าง / บาน
  ('กระจกเป็นรอย', 'Scratched glass'),
  ('กระจกไม่แน่น', 'Loose glass'),
  ('กระจกไม่ได้ขนาด', 'Glass wrong size'),
  ('กันสีขอบวงกบไม่ตรง', 'Crooked paint line at jamb edge'),
  ('กันสีขอบเฟรมไม่ตรง', 'Crooked paint line at frame edge'),
  ('ชุดล็อคติดขัด', 'Lock set jams'),
  ('ชุดล็อคฝืด', 'Lock set stiff'),
  ('ชุดล็อคยังไม่ติดตั้ง', 'Lock set not installed'),
  ('ชุดล็อคเบียด', 'Lock set rubbing'),
  ('ชุดล็อคไม่ตรงเบ้ารับ', 'Lock misaligned with strike plate'),
  ('ติดตั้งบานตายไม่แน่น', 'Fixed panel loosely installed'),
  ('ทำความสะอาดราง', 'Track needs cleaning'),
  ('น้ำขังราง', 'Water pooling in track'),
  ('น้ำเข้าสันบาน', 'Water entering panel edge'),
  ('บานกระพือ', 'Panel flaps'),
  ('บานขบกัน', 'Panels clash'),
  ('บานขูดราง', 'Panel scrapes track'),
  ('บานชนเฟรม', 'Panel hits frame'),
  ('บานตึง', 'Panel tight'),
  ('บานตก', 'Door sagging'),
  ('บานประตูยังไม่ติดตั้ง', 'Door leaf not installed'),
  ('บานฝืด', 'Panel stiff'),
  ('บานสั่น', 'Panel vibrates'),
  ('บานเบียด', 'Panel rubbing'),
  ('บานเป็นรอย', 'Panel scratched'),
  ('บานเอียง', 'Panel misaligned'),
  ('บานแอ่น', 'Panel warped'),
  ('บานโก่ง', 'Panel bowed'),
  ('บานไม่ได้ระดับ', 'Panel not level'),
  ('บานใช้งานยาก', 'Panel difficult to operate'),
  ('ปิดประตูไม่ได้', 'Door cannot close'),
  ('ปิดสองจังหวะ', 'Needs two pushes to close'),
  ('ปิดไม่สนิท', 'Does not close fully'),
  ('ผิวขอบบานไม่เรียบ', 'Rough panel edge'),
  ('ผิวบานไม่เรียบ', 'Rough panel surface'),
  ('ผิววงกบไม่เรียบ', 'Rough jamb surface'),
  ('ผิวเฟรมไม่เรียบ', 'Rough frame surface'),
  ('พบช่องแสง', 'Light gap visible'),
  ('ยังไม่ติดตั้ง Door stopper', 'Door stopper not installed'),
  ('ยังไม่ติดตั้งกันแมลง', 'Insect seal not installed'),
  ('ยังไม่ติดตั้งรูรับกลอนประตู', 'Bolt strike not installed'),
  ('ยังไม่เจาะรูรับกลอนประตู', 'Bolt hole not drilled'),
  ('ยังไม่ติดตั้งสักหลาด', 'Weatherstrip not installed'),
  ('สักหลาดหลุด', 'Weatherstrip detached'),
  ('ยางขาด', 'Rubber seal torn'),
  ('ยางหลุด', 'Rubber seal detached'),
  ('รอยร้าวรอยต่อขอบวงกบ', 'Crack at jamb edge joint'),
  ('รอยร้าวรอยต่อขอบเฟรม', 'Crack at frame edge joint'),
  ('รางเป็นรอย', 'Track scratched'),
  ('ล็อคยาก', 'Hard to lock'),
  ('ล็อคสองจังหวะ', 'Needs two attempts to lock'),
  ('ล็อคไม่ได้', 'Cannot lock'),
  ('วงกบเป็นรอย', 'Jamb scratched'),
  ('วงกบเอียง', 'Jamb crooked'),
  ('วงกบโก่งงอ', 'Jamb warped'),
  ('วงกบโค้งงอ', 'Jamb bent'),
  ('วงกบไม่เสมอ', 'Jamb not flush'),
  ('สีบานด่าง', 'Blotchy panel paint'),
  ('สีบานประตูกับวงกบประตูไม่เหมือนกัน', 'Door leaf and jamb colours do not match'),
  ('สีวงกบด่าง', 'Blotchy jamb paint'),
  ('สีวบกบด่าง', 'Blotchy jamb paint'),
  ('สีวงกบประตูเก่า', 'Door jamb paint worn'),
  ('สีเฟรมด่าง', 'Blotchy frame paint'),
  ('หน้าบานไม่เสมอ', 'Panels not flush'),
  ('หน้าบานไม่เสมอกัน', 'Panels not flush with each other'),
  ('หน้าบานไม่เสมอขอบวงกบ', 'Panel not flush with jamb'),
  ('เดือยล็อคแข็ง', 'Lock latch stiff'),
  ('เบ้ากุญแจไม่ลงล็อค', 'Latch does not engage strike'),
  ('เปิด-ปิด มีเสียง', 'Noisy when opening / closing'),
  ('เปิด-ปิด ติดขัด', 'Jams when opening / closing'),
  ('เปิด-ปิด ยาก', 'Hard to open / close'),
  ('เปิด/ปิด ยาก', 'Hard to open / close'),
  ('เฟรมเป็นรอย', 'Frame scratched'),
  ('เลื่อนสะดุด', 'Sliding not smooth'),
  ('เลื่อนมีเสียง', 'Noisy when sliding'),
  ('เลื่อนฝืด', 'Sliding stiff'),
  ('ไม่ทาสีขอบบาน', 'Panel edges not painted'),
  ('ไม่ทาสีสันบาน', 'Panel side edge not painted'),
  ('เก็บสีขอบบานไม่เรียบร้อย', 'Untidy paint on panel edges'),

  -- มุ้งลวด / ม่าน
  ('มุ้งลวดขาด', 'Torn screen mesh'),
  ('มุ้งลวดย่น', 'Wrinkled screen mesh'),
  ('แม่เหล็กไม่ดูด', 'Magnet does not hold'),
  ('ติดตั้งราวผ้าม่านไม่ได้ระดับ', 'Curtain rail not level'),
  ('ติดตั้งรางไม่ได้ระดับ', 'Track not level'),
  ('ผ้าถลอก/ขาด', 'Fabric frayed / torn'),
  ('ยังไม่ติดตั้งตะขอเกี่ยวผ้าม่าน', 'Curtain hooks not installed'),

  -- ปลั๊ก / สวิตช์ / แสงสว่าง
  ('L กับ G สลับกัน', 'L and G swapped'),
  ('L กับ N สลับกัน', 'L and N swapped'),
  ('N กับ G สลับกัน', 'N and G swapped'),
  ('กันดูดไม่ทำงาน', 'RCD not working'),
  ('ติดตั้งปลั๊กวงจรเดียวกับแสงสว่าง', 'Outlet on same circuit as lighting'),
  ('ติดตั้งแสงสว่างวงจรเดียวกับปลั๊ก', 'Lighting on same circuit as outlets'),
  ('ปลั๊กละลาย', 'Outlet melted'),
  ('สาย RG6 ช็อต', 'RG6 cable shorted'),
  ('เข้าหัวสายผิด', 'Incorrect cable termination'),
  ('แผ่นกันดูดแข็ง (เสียบยาก)', 'Safety shutter stiff (hard to plug in)'),
  ('แรงดันไฟตก', 'Voltage drop'),
  ('ไม่พบปลั๊กตามแบบแปลนระบุ', 'Outlet shown on plan not found'),
  ('ไม่พบสาย G', 'No ground (G) wire'),
  ('ไม่พบสาย N', 'No neutral (N) wire'),
  ('ไม่พบไฟเข้าปลั๊ก', 'No power at outlet'),
  ('senser ไม่ทำงาน', 'Sensor not working'),
  ('ตอนเปิดไฟมีเสียงดัง', 'Loud noise when light switched on'),
  ('ติดตั้งดวงโคมผิดประเภท', 'Wrong type of light fixture installed'),
  ('ติดตั้งแนวโคมไม่ตรง', 'Light fixtures not aligned'),
  ('น้ำเข้าสวิตซ์ไฟ', 'Water in light switch'),
  ('น้ำเข้าโคมไฟ', 'Water in light fixture'),
  ('สวิตซ์จม', 'Switch recessed'),
  ('สวิตซ์ติดขัด', 'Switch sticks'),
  ('สวิตซ์ฝืด', 'Switch stiff'),
  ('สวิตซ์เอียง', 'Switch crooked'),
  ('สวิตซ์ไม่ลงล็อค', 'Switch not seated'),
  ('หลอดไฟไม่ติด', 'Bulb not working'),
  ('เข้าสายไฟไม่แน่น', 'Loose wire connection'),
  ('เปิด-ปิด กลับด้าน', 'Switch on / off reversed'),
  ('แสงไฟไม่สม่ำเสมอตลอดเส้น', 'Uneven light along strip'),
  ('ไฟกระพริบ', 'Light flickers'),
  ('ไม่พบดวงโคมตามแบบแปลนระบุ', 'Light fixture shown on plan not found'),
  ('ไม่พบสวิตซ์ตามแบบแปลนระบุ', 'Switch shown on plan not found'),
  ('ไม่พบสายดับของสวิตซ์', 'Switched wire not found'),

  -- ระบบไฟฟ้า / ตู้ไฟ / Junction Box
  ('Bar Neutral ติดกัน', 'Neutral bars bridged'),
  ('Emergency light Battery เสื่อม', 'Emergency light battery degraded'),
  ('Emergency light Battery ไม่เก็บไฟ', 'Emergency light battery not holding charge'),
  ('Emergency light ไม่ทำงาน', 'Emergency light not working'),
  ('Ground Rod มีค่าความต้านทานมากว่า 5 โอห์ม', 'Ground rod resistance above 5 ohms'),
  ('Spec อุปกรณ์ไม่ตรง', 'Equipment not to spec'),
  ('Support ท่อไม่ได้มาตรฐาน', 'Conduit supports not to standard'),
  ('ขนาดลูก circuit ไม่ตรงตามตารางโหลด', 'Breaker size does not match load schedule'),
  ('ขนาดลูก circuit ไม่เพียงพอกับ Load ที่ใช้', 'Breaker undersized for load'),
  ('ขนาดสายเล็กกว่าพิกัดลูก circuit', 'Wire gauge smaller than breaker rating'),
  ('ข้อต่อท่อหลุด', 'Conduit fitting detached'),
  ('คู่สาย Line,Neutral ไม่ครบคู่', 'Line / Neutral pairs incomplete'),
  ('จัดสายไม่เป็นระเบียบ', 'Messy wiring'),
  ('ฉนวนสายฉีกขาด', 'Torn cable insulation'),
  ('ติดตั้ง Junction Box ไม่เรียบร้อย', 'Junction box installed untidily'),
  ('ติดตั้ง Rack ไม่เรียบร้อย', 'Rack installed untidily'),
  ('ติดตั้งตู้เอียง', 'Panel installed crooked'),
  ('ติดตั้งราง wire way ไม่เรียบร้อย', 'Wireway installed untidily'),
  ('ติดตั้งลูก circuit เอียง', 'Breaker installed crooked'),
  ('ทองแดงถูกตัด(เข้าสายไม่ครบทุกเส้น)', 'Copper strands cut (not all strands terminated)'),
  ('ทองแดงโผล่', 'Exposed copper'),
  ('น้ำขังบ่อ', 'Water pooling in pit'),
  ('น้ำเข้าตู้ไฟ', 'Water in electrical panel'),
  ('ปากบ่อต่ำกว่าระดับดิน', 'Pit opening below ground level'),
  ('ฝาตู้เปิด-ปิดยาก', 'Panel door hard to open / close'),
  ('ฝาตู้เปิดไม่ได้', 'Panel door will not open'),
  ('ฝาบ่อแตก', 'Pit cover cracked'),
  ('ยังไม่ติดตั้ง name plate', 'Name plate not installed'),
  ('ยังไม่ติดตั้ง wire marker', 'Wire markers not installed'),
  ('ยังไม่ติดตั้ง wire nut เก็บปลายสาย', 'Wire nuts not fitted on wire ends'),
  ('ยังไม่ติดตั้งกันดูด', 'RCD not installed'),
  ('ยังไม่ติดตั้งกันบาดสาย', 'Cable edge protection not installed'),
  ('ยังไม่ติดตั้งปลอกหุ้ม Bar Line', 'Line bar cover not installed'),
  ('ยังไม่เก็บสายไฟที่ยกเลิก', 'Abandoned wiring not removed'),
  ('ยังไม่เข้าสาย Main', 'Main cable not connected'),
  ('ยิง PU foam ปิดปากท่อไม่เรียบร้อย', 'Untidy PU foam sealing at conduit ends'),
  ('ลำดับ Phase ผิด', 'Incorrect phase sequence'),
  ('สาย Main Neutral ไม่เข้าที่ Bar Ground ก่อน', 'Main neutral not bonded to ground bar first'),
  ('สาย Main ถูกตัด', 'Main cable cut'),
  ('สายไฟร้อยท่อไม่สุด', 'Wiring not fully enclosed in conduit'),
  ('สายไฟไม่ร้อยท่อ', 'Wiring not run in conduit'),
  ('สีสายผิดมาตรฐานกำหนด', 'Wire colours not to standard'),
  ('ห้ามใช้สายเชื่อม Bar Neutral', 'Do not bridge neutral bars with wire'),
  ('เก็บงานขอบตู้ไม่เรียบร้อย', 'Untidy finishing at panel edge'),
  ('เข้าสายมากว่า 1 เส้น (ควรเข้า 1 เส้น/CB)', 'More than one wire per breaker (should be 1 per CB)'),
  ('เข้าสายไม่แน่น', 'Loose wire termination'),
  ('เปิดหน้ากากตู้ไม่ได้', 'Panel cover will not open'),
  ('เอาซิลิโคนขอบตู้ออก', 'Remove silicone from panel edge'),
  ('โรยหินก้นบ่อ', 'Add gravel to pit bottom'),
  ('ใส่หินกรวดก้นบ่อ', 'Add gravel to pit bottom'),
  ('ใช้ท่อ/ราง ผิดประเภท', 'Wrong type of conduit / trunking'),
  ('ไม่ปิดช่องต่อท่อของ Junction Box', 'Junction box knockouts not sealed'),
  ('ไม่ปิดฝา Junction Box', 'Junction box cover not closed'),
  ('ไม่ยึด Junction Box กับแนวผนังหรือโครงหลังคา', 'Junction box not secured to wall or roof structure'),
  ('ยังไม่ปิดฝาบล็อค', 'Box cover not closed'),
  ('ยังไม่ปิดรูต่อท่อ', 'Conduit openings not sealed'),
  ('ไม่ต่อ Connector', 'Connector not fitted'),
  ('ค่าความต้านทานเกิน 5 โอห์ม ซึ่งสูงกว่ามาตรฐานกำหนด', 'Resistance exceeds 5 ohms, above the required standard'),

  -- เครื่องปรับอากาศ
  ('ติดตั้งแอร์เอียงผิดฝั่ง', 'AC unit tilted the wrong way'),
  ('น้ำยาแอร์ซึมลงฝ้า', 'AC refrigerant leaking into ceiling'),
  ('น้ำแอร์หยด', 'AC dripping water'),
  ('แอร์ทำงานเสียงดัง', 'AC noisy'),
  ('แอร์ไม่ทำงาน', 'AC not working'),
  ('แอร์ไม่เย็น', 'AC not cooling'),
  ('ไม่มีฉนวนหุ้ม', 'Missing insulation'),
  ('ไม่มีรางครอบ', 'No trunking cover'),
  ('ไอน้ำเกาะหน้ากากแอร์', 'Condensation on AC front panel'),

  -- กระเบื้อง / หิน
  ('Slope พื้นเกินค่ามาตรฐาน', 'Floor slope exceeds standard'),
  ('กระเดิด', 'Lifted'),
  ('ขอบกระเบื้องคม', 'Sharp tile edges'),
  ('ขอบคิ้วคม', 'Sharp trim edges'),
  ('คิ้วกระเดิด', 'Trim lifted'),
  ('คิ้วเป็นรอย', 'Trim scratched'),
  ('ปูกระเบื้องไม่ตรงแนวห้อง', 'Tiles not aligned with room'),
  ('ปูนไม่เต็ม', 'Hollow (incomplete mortar bed)'),
  ('ปูไม่ชนขอบ', 'Not laid up to edge'),
  ('ผิวหน้าเป็นรอยตาราง', 'Grid marks on surface'),
  ('พื้นไม่ได้ระดับ', 'Floor not level'),
  ('ยังไม่ติดตั้งคิ้ว', 'Trim not installed'),
  ('ยาแนวสกปรก', 'Dirty grout'),
  ('ยาแนวไม่สม่ำเสมอ', 'Uneven grout'),
  ('ยาแนวไม่เต็มร่อง', 'Grout not filling joints'),
  ('รอยต่อคิ้วไม่เรียบร้อย', 'Untidy trim joint'),
  ('รอยร้าวผิวหน้า', 'Surface crack'),
  ('ร่องยาแนวไม่ตรงกัน', 'Grout lines misaligned'),
  ('ร่อน', 'Debonded'),
  ('แนวกระเบื้องไม่ตรง', 'Tile lines not straight'),
  ('กระเบื้องบิ่น', 'Tile chipped'),
  ('กระเบื้องแตก', 'Tile cracked'),

  -- พื้นยาง / ลามิเนต / ไม้
  ('ตัวจบยวบ', 'End trim sags'),
  ('ตัวจบโก่ง', 'End trim warped'),
  ('ตัวจบไม่ได้ระนาบ', 'End trim not flush'),
  ('ตัวจบไม่แน่น', 'End trim loose'),
  ('ติดตั้งตัวจบไม่แน่น', 'End trim loose'),
  ('พื้นนูน', 'Floor bulging'),
  ('พื้นบวม', 'Floor swollen'),
  ('พื้นบวม/พอง', 'Floor swollen / bulging'),
  ('พื้นยวบ', 'Floor springy'),
  ('รอยต่อแผ่นกระเดิด', 'Plank joints lifted'),
  ('รอยต่อแผ่นขึ้นตะเข็บ', 'Plank joints peaking'),
  ('รอยต่อแผ่นห่าง', 'Gaps between planks'),
  ('รอยต่อแผ่นโก่ง', 'Plank joints warped'),
  ('รอยต่อแผ่นไม่เสมอกัน', 'Sheet joints not flush'),
  ('เหยียบมีเสียง', 'Squeaks when walked on'),
  ('ผิวไม้เป็นเสี้ยน', 'Wood splintering'),
  ('ผิวไม้ไม่เรียบ', 'Uneven wood surface'),
  ('ยังไม่เก็บงานสี', 'Paint finishing incomplete'),
  ('สีไม้ไม่สม่ำเสมอ', 'Uneven wood colour'),
  ('สีไม้ไม่เหมือนกัน', 'Wood colours do not match'),
  ('หัวตะปูโผล่', 'Nail heads protruding'),
  ('หัวน็อตโผล่', 'Screw heads protruding'),
  ('ไม้สีเพี้ยน', 'Wood discoloured'),
  ('ไม้แอ่น', 'Wood cupped'),
  ('ไม้โก่ง/งอ', 'Wood bowed / bent'),

  -- พื้นคอนกรีต
  ('ขอบบิ่น/แตก', 'Chipped / broken edges'),
  ('ปูนร่อน', 'Surface flaking'),
  ('พื้นทรุด', 'Floor subsidence'),
  ('พื้นทรุดตัว', 'Floor subsidence'),
  ('พื้นเป็นรู', 'Holes in floor'),
  ('ยังไม่ขัดเก็บผิวหน้า', 'Surface not yet polished'),
  ('ยังไม่เก็บขอบ', 'Edges not finished'),
  ('รางระบายน้ำตัน', 'Drain channel blocked'),

  -- สวน
  ('ดินทรุด', 'Soil subsidence'),
  ('ต้นไม้แห้งตาย', 'Plants dried / dead'),
  ('ต้นไม้ไม่ได้แนว', 'Plants not in line'),
  ('ยังไม่ปรับหน้าดิน', 'Ground surface not levelled'),
  ('หญ้าขึ้นไม่สม่ำเสมอ', 'Grass growing unevenly'),
  ('หญ้าเหลืองตาย', 'Grass yellowed / dead'),
  ('หินทางเดินบิ่น/แตก', 'Stepping stones chipped / broken'),
  ('หินทางเดินไม่ได้ระดับ', 'Stepping stones not level'),

  -- บัว
  ('รอยต่อบัวกระเดิด', 'Moulding joints lifted'),
  ('เก็บรอยตะปูไม่เรียบร้อย', 'Nail holes not filled neatly'),
  ('เก็บรอยตัวตะปูไม่เรียบร้อย', 'Nail holes not filled neatly'),
  ('น้ำย้อน', 'Water tracking back'),
  ('ร่องน้ำหยดไม่ตรง', 'Drip groove not straight'),
  ('เก็บงานหลังบัวไม่เรียบร้อย', 'Untidy finish on top of moulding'),

  -- ผนัง / วอลล์เปเปอร์
  ('ฉาบตะแกรงกงไก่ไม่เรียบร้อย', 'Untidy plaster over wire mesh'),
  ('น้ำรั่วซึมเข้ารอยต่อบัวปูน', 'Water leaking through cement moulding joint'),
  ('น้ำรั่วซึมเข้ารอยต่อแผ่น', 'Water leaking through panel joints'),
  ('ผนังนูน', 'Wall bulging'),
  ('ผนังล้มดิ่ง', 'Wall out of plumb'),
  ('ผนังเว้า', 'Wall concave'),
  ('ผนังไม่ได้ฉาก', 'Wall not square'),
  ('ผิวฉาบร่อน', 'Plaster debonding'),
  ('ผิวเป็นคลื่น', 'Wavy surface'),
  ('รูตามด', 'Pinholes'),
  ('เก็บงานตีนผนังไม่เรียบร้อย', 'Untidy finish at wall base'),
  ('เก็บสีตีนผนังไม่เรียบร้อย', 'Untidy paint at wall base'),
  ('แนวผนังไม่ตรง', 'Wall line not straight'),
  ('กาวร่อน/ไม่แนบผนัง', 'Adhesive failing / not adhered to wall'),
  ('รอยต่อวอลล์เปเปอร์ไม่เรียบร้อย', 'Untidy wallpaper seams'),
  ('รอยปะไม่เรียบร้อย/ไม่เนียน', 'Patch repair not seamless'),

  -- เฟอร์นิเจอร์
  ('Soft close มีปัญหา', 'Soft-close faulty'),
  ('ไม่ติดตั้ง Soft close', 'Soft-close not installed'),
  ('ติดตั้งมือจับไม่แน่น', 'Handle loose'),
  ('ติดตั้งมือจับไม่ได้ระดับ', 'Handle not level'),
  ('ติดตั้งหน้าบานไม่เสมอกัน', 'Door fronts not flush'),
  ('ติดตั้งหน้าบานไม่แน่น', 'Door front loose'),
  ('ติดตั้งหน้าบานไม่ได้ดิ่ง', 'Door front not plumb'),
  ('ติดตั้งหน้าบานไม่ได้ระดับ', 'Door front not level'),
  ('วัสดุปิดผิวลอก', 'Surface laminate peeling'),
  ('แนวหน้าบานไม่ตรง', 'Door fronts misaligned'),

  -- ฝ้า
  ('ติดตั้งฝ้าไม่ได้ระดับ', 'Ceiling not level'),
  ('ฝ้าตกท้องช้าง', 'Ceiling sagging'),
  ('พบหนูเหนือฝ้า', 'Rodents found above ceiling'),
  ('เก็บงานฝ้าดรอปไม่เรียบร้อย', 'Untidy drop ceiling finish'),

  -- ปลวก / ตู้จดหมาย / ถังขยะ
  ('ท่อแตก/ท่อหัก', 'Pipe cracked / broken'),
  ('ปิดกล่องไม่สนิท', 'Box not fully closed'),
  ('พบรังปลวก', 'Termite nest found'),
  ('เพิ่มแคมป์รัดท่อ', 'Add pipe clamps'),
  ('แคมป์รัดท่อหลุด', 'Pipe clamp detached'),
  ('เก็บความสะอาดภายใน', 'Interior needs cleaning'),

  -- สระว่ายน้ำ / ประปา / สุขภัณฑ์
  ('ค่า PH ไม่ได้มาตรฐาน', 'pH not within standard'),
  ('ตรวจสอบระบบน้ำวนมีปัญหา', 'Circulation system faulty'),
  ('ปั๊มไม่ทำงาน', 'Pump not working'),
  ('ทำความสะอาดถังน้ำดี', 'Clean water tank needs cleaning'),
  ('น้ำไม่ไหล', 'No water flow'),
  ('น้ำไหลเบา', 'Low water flow'),
  ('ลูกลอยยังไม่ได้ติดตั้ง', 'Float valve not installed'),
  ('ลูกลอยไม่ทำงาน', 'Float valve not working'),
  ('แป้นท่อจมผนัง', 'Pipe flange recessed into wall'),
  ('Overflow ระบายช้า', 'Overflow drains slowly'),
  ('ท่อตัน', 'Pipe blocked'),
  ('น้ำซึมข้อต่อ', 'Leak at fitting'),
  ('น้ำซึมข้อต่อ Overflow', 'Leak at overflow fitting'),
  ('น้ำซึมข้อต่อท่อน้ำดี', 'Leak at supply pipe fitting'),
  ('น้ำซึมข้อต่อท่อน้ำทิ้ง', 'Leak at waste pipe fitting'),
  ('ยังไม่ทดสอบการใช้งาน', 'Not yet function-tested'),
  ('สะดืออ่างขังน้ำไม่อยู่', 'Basin plug does not hold water'),
  ('ท่อน้ำร้อน น้ำเย็นสลับกัน', 'Hot and cold pipes swapped'),
  ('น้ำไม่ร้อน', 'No hot water'),
  ('ปั๊มน้ำไม่ตัด', 'Pump does not cut off'),
  ('เครื่องปั๊มน้ำไม่ทำงาน', 'Water pump not working'),

  -- สุขาภิบาล / FD-RD
  ('Slope ท่อไม่ได้', 'Incorrect pipe slope'),
  ('ขุดลอก', 'Needs dredging'),
  ('ข้องอคว่ำไม่จมน้ำ', 'Inverted elbow not submerged'),
  ('ท่อแตก', 'Pipe cracked'),
  ('น้ำย้อนเข้าบ้าน', 'Water backflowing into house'),
  ('น้ำออกท่ออากาศ', 'Water coming out of vent pipe'),
  ('น้ำไม่ระบายออกบ่อสาธารณะ', 'Water not draining to public sewer'),
  ('ปรับเทลีนก้นบ่อพัก', 'Re-slope manhole bottom'),
  ('ยังไม่เกร้าท์รอยต่อ', 'Joints not yet grouted'),
  ('เกร้าท์รอยต่อไม่เรียบร้อย', 'Untidy grouted joints'),
  ('ไม่ติดตั้งท่ออากาศ', 'Vent pipe not installed'),
  ('ไม่มีตะแกรงปิดท่ออากาศ', 'No mesh cover on vent pipe'),
  ('ไม่ใส่ข้องอดักกลิ่น', 'No P-trap installed'),
  ('น้ำระบายช้า', 'Slow drainage'),
  ('พบเศษปูนในท่อ', 'Mortar debris in pipe'),

  -- หลังคา
  ('ครอบหลังคาไม่ลงล็อค', 'Ridge caps not seated'),
  ('พบรังนก', 'Bird nest found'),
  ('แผ่นเพจเยื้องเสา', 'Plate offset from column'),

  -- ราวกันตก / บันได
  ('ติดตั้งฝาคราบไม่เรียบร้อย', 'Untidy cover plate installation'),
  ('ขนาดลูกนอนไม่ได้มาตรฐาน', 'Tread depth not to standard'),
  ('ความสูงลูกตั้งไม่ได้มาตรฐาน', 'Riser height not to standard'),
  ('ผิวลูกตั้งไม่เรียบ', 'Uneven riser surface'),
  ('รอยร้าวรอยต่อตามขั้นบันได', 'Cracks along stair step joints'),
  ('รอยหัวตะปู', 'Nail head marks'),
  ('ระยะห่างระหว่างลูกตั้งเกินค่ามาตรฐาน', 'Gap between risers exceeds standard'),
  ('สีลูกตั้งด่าง', 'Blotchy riser paint'),

  -- ประตูรั้ว / รั้ว
  ('ติดตั้งบูทเหล็กรับรั้วไม่แน่น', 'Gate steel bracket loose'),
  ('ติดตั้งเฟรมแอลไม่แน่น', 'L-frame loose'),
  ('น้ำเข้าในโครงเหล็กรั้ว', 'Water inside steel gate frame'),
  ('มอเตอร์ไม่ทำงาน', 'Motor not working'),
  ('ยังไม่ตรวจสอบการใช้งาน', 'Operation not yet checked'),
  ('รั้วชนบ่ารับ', 'Gate hits stopper'),
  ('รั้วไหลกลับ', 'Gate rolls back'),
  ('รางจมพื้น', 'Track sunk into floor'),
  ('รางรอยจากพื้นสูง', 'Track raised above floor'),
  ('ล้อรั้วตกราง', 'Gate wheel off track'),
  ('แนวรั้วไม่ตรง', 'Fence line not straight'),

  -- บ่อบำบัด / บ่อดักไขมัน
  ('จัดแผงมีเดียร์ใหม่', 'Rearrange media panels'),
  ('แผงมีเดียร์ชำรุด', 'Media panels damaged'),
  ('ติดตั้งถังต่ำกว่าระดับมาตรฐาน', 'Tank installed below standard level'),
  ('ถังแตกชำรุด', 'Tank cracked / damaged'),
  ('ฝาบ่อต่ำกว่าระดับดิน', 'Cover below ground level'),
  ('ฝาบ่อสูงกว่าระดับดิน', 'Cover above ground level'),
  ('ระดับน้ำต่ำกว่ามาตรฐาน', 'Water level below standard'),
  ('ระดับน้ำสูงกว่ามาตรฐาน', 'Water level above standard'),
  ('เปิดฝายาก', 'Cover hard to open'),
  ('ตระกร้าชำรุด', 'Basket damaged'),
  ('ยังไม่ใส่ตระกร้า', 'Basket not installed'),

  -- โครงสร้าง
  ('คานหัก', 'Broken beam'),
  ('รอยร้าวทะลุผนัง', 'Crack through wall'),
  ('เสาหัก', 'Broken column'),
  ('โครงสร้างทรุดตัว', 'Structural settlement')
) AS m(th, en)
WHERE btrim(s.name) = m.th
  AND s.name_en IS NULL;

-- PDF ภาษาอังกฤษที่ cache ไว้ใช้ hash จากข้อมูล defect เท่านั้น (ดู ReportsService.computeDataHash)
-- การเติม name_en ไม่เปลี่ยน hash จึงต้องล้าง hash อังกฤษ ให้ render ใหม่ครั้งถัดไปที่มีคนเปิด
UPDATE inspection_round SET last_pdf_hash_en = NULL WHERE last_pdf_hash_en IS NOT NULL;

COMMIT;

-- ── ตรวจหลังรัน: ควรได้ 0 แถว ถ้ามีแถวโผล่แปลว่าชื่อไทยใน DB ไม่ตรงกับในไฟล์นี้ ──
-- SELECT category_id, name FROM defect_category WHERE name_en IS NULL;
-- SELECT sub_category_id, name, category_id FROM defect_sub_category WHERE name_en IS NULL;
